version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  backend-damri:
    build: .
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - mongo_db

volumes:
  mongo_db: